// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuatY95dIT_c3DifA_PAk_kOfrUqdsNpE',
    appId: '1:174763139313:web:fe4278778feb64463f4950',
    messagingSenderId: '174763139313',
    projectId: 'dietapp-7df25',
    authDomain: 'dietapp-7df25.firebaseapp.com',
    storageBucket: 'dietapp-7df25.firebasestorage.app',
    measurementId: 'G-G2XP1P6P0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxKsWxIrSFKyI-uZokRxA0HV4jbz1rHk',
    appId: '1:174763139313:android:c254729242c04baa3f4950',
    messagingSenderId: '174763139313',
    projectId: 'dietapp-7df25',
    storageBucket: 'dietapp-7df25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4Ns9UpN7QnPz145HjOLaHIZ5u2yeVMQ',
    appId: '1:174763139313:ios:6ff5309daf46ee233f4950',
    messagingSenderId: '174763139313',
    projectId: 'dietapp-7df25',
    storageBucket: 'dietapp-7df25.firebasestorage.app',
    iosBundleId: 'com.example.longevityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4Ns9UpN7QnPz145HjOLaHIZ5u2yeVMQ',
    appId: '1:174763139313:ios:6ff5309daf46ee233f4950',
    messagingSenderId: '174763139313',
    projectId: 'dietapp-7df25',
    storageBucket: 'dietapp-7df25.firebasestorage.app',
    iosBundleId: 'com.example.longevityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuatY95dIT_c3DifA_PAk_kOfrUqdsNpE',
    appId: '1:174763139313:web:adfd2839d15475353f4950',
    messagingSenderId: '174763139313',
    projectId: 'dietapp-7df25',
    authDomain: 'dietapp-7df25.firebaseapp.com',
    storageBucket: 'dietapp-7df25.firebasestorage.app',
    measurementId: 'G-9BS838LHMW',
  );
}
